[package]
name = "fontquant"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
font-types = { workspace = true }
fontquant-lib = { path = "../fontquant-lib" }
indicatif = { version = "0.17.11", features = ["rayon"] }
log = { workspace = true }
rayon = "1.10.0"
read-fonts = { workspace = true }
skrifa = { workspace = true }
write-fonts = { workspace = true }
